### PR TITLE
Loginfix

### PR DESCRIPTION
**Pull request by jUnion44**
Login screen now redirects to home page when user is logged in.

### CODE REVIEW

**Comment by codingdn** [comment]
this PR is very confusing. Can you link the notion task associated since it looks like there is code from other assignments as well

**Comment by jUnion44** [comment]
I think I accidentally pulled master into my branch for a previous task instead of switching back to master first or something like that.

https://www.notion.so/h4i/Bug-Going-back-while-logged-in-can-go-to-login-page-as-if-they-logged-out-212539680060471f8cd7bc95a4a186e8 was the task that this PR was intended to accomplish.

**Comment by jUnion44** [comment]
After investigation it looks like I accidentally put two tasks into the same branch.

**Comment by jUnion44** [comment]
Merge conflicts resolved.

**Comment by codingdn** [comment]
Just remember to be mindful of what branch you are working on next time

**Pull request merged**
